# frontend/nginx.conf
server {
    listen 80;

    # Si alguien pide la web, dale el index.html
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Si alguien pide /api, envíalo a la caja del Backend
    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
